// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddressAutocompleteController from "./address_autocomplete_controller"
application.register("address-autocomplete", AddressAutocompleteController)

import CreateSiteMapController from "./create_site_map_controller"
application.register("create-site-map", CreateSiteMapController)

import DiveSitesFiltersController from "./dive_sites_filters_controller"
application.register("dive-sites-filters", DiveSitesFiltersController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapController from "./map_controller"
application.register("map", MapController)

import SignUpController from "./sign_up_controller"
application.register("sign-up", SignUpController)

import StarRatingController from "./star_rating_controller"
application.register("star-rating", StarRatingController)

import ToggleFavoriteController from "./toggle_favorite_controller"
application.register("toggle-favorite", ToggleFavoriteController)
